parser: babel-eslint
env:
  browser: true
  es6: true
  jest: true
extends:
- eslint:recommended
- plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 10
  sourceType: module
plugins:
- react-hooks
- react
rules:
  no-async-promise-executor: off
  react/prop-types: off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  brace-style:
    - error
    - stroustrup
